<?php
/**
 * Funciones del sistema RSVP
 * Archivo separado para mejor organización del código
 */

/**
 * Configuración SMTP para WordPress
 */
function configurar_smtp($phpmailer) {
    $phpmailer->isSMTP();
    $phpmailer->Host = 'smtp.hostinger.com';
    $phpmailer->SMTPAuth = true;
    $phpmailer->Port = 465;
    $phpmailer->Username = 'rsvp@thekalkavans2025.com';
    $phpmailer->Password = 'eoq}80xrhsT3';
    $phpmailer->SMTPSecure = 'ssl';
    $phpmailer->From = 'rsvp@thekalkavans2025.com';
    $phpmailer->FromName = 'Asil & Brenda\'s Wedding';
}

// Hook para WordPress
add_action('phpmailer_init', 'configurar_smtp');

/**
 * Function to send email to administrator
 */
function sendAdminEmail($guest_name, $guests, $allergies, $email) {
    $admin_email = 'rsvp@thekalkavans2025.com';
    $subject = '✉️ New RSVP - ' . $guest_name;
    
    // Generate detailed list by event
    $event_names = [
        'ceremony' => 'CEREMONY (December 13th, 5:00 PM)',
        'reception' => 'RECEPTION (December 13th, Following the ceremony)',
        'welcome' => 'WELCOME PARTY (December 12th, 6:00 PM)',
        'brunch' => 'FAREWELL BRUNCH (December 14th, 10:00 AM - 2:00 PM)'
    ];
    
    $total_accepts = 0;
    $total_declines = 0;
    foreach ($guests as $event => $guest_responses) {
        foreach ($guest_responses as $response) {
            if ($response === 'accept') $total_accepts++;
            else $total_declines++;
        }
    }
    
    $message = '
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <style>
            body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
            .header { background: #8B9467; color: white; padding: 20px; text-align: center; }
            .content { padding: 20px; background: #f9f9f9; }
            .event-section { margin: 15px 0; padding: 15px; background: white; border-left: 4px solid #8B9467; }
            .guest-item { margin: 5px 0; padding: 8px; background: #f5f5f5; }
            .accept { color: #5A6B3A; font-weight: bold; }
            .decline { color: #cc0000; font-weight: bold; }
            .summary { background: #e8f5e8; padding: 15px; margin: 20px 0; border-radius: 5px; }
            .footer { text-align: center; padding: 20px; font-size: 12px; color: #666; }
        </style>
    </head>
    <body>
        <div class="header">
            <h1>🎉 New RSVP Received</h1>
            <p>Asil & Brenda\'s Wedding</p>
        </div>
        
        <div class="content">
            <div class="summary">
                <h2>📋 Summary</h2>
                <p><strong>Primary Guest:</strong> ' . $guest_name . '</p>
                <p><strong>Email:</strong> ' . $email . '</p>
                <p><strong>Total Accepts:</strong> <span class="accept">' . $total_accepts . '</span></p>
                <p><strong>Total Declines:</strong> <span class="decline">' . $total_declines . '</span></p>
                <p><strong>Date:</strong> ' . date('Y-m-d H:i:s') . '</p>
            </div>
            
            <h2>📅 Confirmations by Event</h2>';
    
    foreach ($event_names as $event_id => $event_name) {
        $message .= '<div class="event-section">';
        $message .= '<h3>' . $event_name . '</h3>';
        if (isset($guests[$event_id])) {
            foreach ($guests[$event_id] as $name => $response) {
                $class = $response === 'accept' ? 'accept' : 'decline';
                $status = $response === 'accept' ? '✅ ACCEPTS' : '❌ DECLINES';
                $message .= '<div class="guest-item"><span class="' . $class . '">' . $name . ': ' . $status . '</span></div>';
            }
        }
        $message .= '</div>';
    }
    
    $message .= '
            <div class="event-section">
                <h3>🍽️ Allergies/Restrictions</h3>
                <p>' . ($allergies ?: 'None reported') . '</p>
            </div>
        </div>
        
        <div class="footer">
            <p>This email was automatically generated by the RSVP system</p>
            <p>Asil & Brenda\'s Wedding - December 13th, 2025 - Cartagena, Colombia</p>
        </div>
    </body>
    </html>';
    
    $headers = [
        'From: rsvp@thekalkavans2025.com',
        'Reply-To: ' . $email,
        'Content-Type: text/html; charset=UTF-8'
    ];
    
    return wp_mail($admin_email, $subject, $message, $headers);
}

/**
 * Function to send email to guest
 */
function sendGuestEmail($guest_name, $email) {
    $subject = '💌 RSVP Confirmation - Asil & Brenda\'s Wedding';
    
    $message = '
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <style>
            body { font-family: "Georgia", serif; line-height: 1.6; color: #333; margin: 0; padding: 0; background: #f5f5f5; }
            .container { max-width: 600px; margin: 0 auto; background: white; }
            .header { background: linear-gradient(135deg, #8B9467, #A5B375); color: white; padding: 40px 30px; text-align: center; }
            .header h1 { margin: 0 0 10px 0; font-size: 28px; font-weight: normal; }
            .header p { margin: 0; font-size: 16px; opacity: 0.9; }
            .content { padding: 40px 30px; }
            .greeting { font-size: 20px; color: #8B9467; margin-bottom: 20px; text-align: center; }
            .message { font-size: 16px; line-height: 1.8; margin-bottom: 30px; text-align: center; }
            .events-container { margin: 30px 0; }
            .event { margin: 20px 0; padding: 20px; background: #f9f9f9; border-left: 4px solid #8B9467; }
            .event-title { font-size: 18px; color: #8B9467; font-weight: bold; margin-bottom: 10px; }
            .event-details { font-size: 14px; color: #666; line-height: 1.6; }
            .event-details strong { color: #333; }
            .footer { background: #8B9467; color: white; padding: 30px; text-align: center; }
            .footer h3 { margin: 0 0 15px 0; font-size: 20px; }
            .footer p { margin: 5px 0; font-size: 14px; opacity: 0.9; }
            .divider { height: 2px; background: linear-gradient(to right, transparent, #8B9467, transparent); margin: 30px 0; }
            .contact-info { background: #e8f5e8; padding: 20px; margin: 20px 0; text-align: center; font-size: 14px; border-radius: 5px; }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>🎉 Thank You for Your RSVP!</h1>
                <p>Asil & Brenda\'s Wedding</p>
            </div>
            
            <div class="content">
                <div class="greeting">
                    Dear ' . $guest_name . ',
                </div>
                
                <div class="message">
                    We have received your confirmation and we are excited to share this special day with you!<br><br>
                    Your presence will make our celebration even more memorable.
                </div>
                
                <div class="divider"></div>
                
                <h2 style="text-align: center; color: #8B9467; margin-bottom: 25px;">📅 Event Details</h2>
                
                <div class="events-container">
                    <div class="event">
                        <div class="event-title">💒 CEREMONY</div>
                        <div class="event-details">
                            <strong>Date:</strong> December 13th, 2025<br>
                            <strong>Time:</strong> 5:00 P.M.<br>
                            <strong>Location:</strong> Baluarte San Francisco Javier<br>
                            <strong>Dress Code:</strong> Black Tie
                        </div>
                    </div>
                    
                    <div class="event">
                        <div class="event-title">🎉 RECEPTION</div>
                        <div class="event-details">
                            <strong>Date:</strong> December 13th, 2025<br>
                            <strong>Time:</strong> Following the ceremony<br>
                            <strong>Location:</strong> Sofitel Legend Santa Clara - Ballroom
                        </div>
                    </div>
                    
                    <div class="event">
                        <div class="event-title">🍸 WELCOME PARTY</div>
                        <div class="event-details">
                            <strong>Date:</strong> December 12th, 2025<br>
                            <strong>Time:</strong> 6:00 P.M.<br>
                            <strong>Location:</strong> Sofitel Legend Santa Clara - Spa Terrace<br>
                            <strong>Dress Code:</strong> Cocktail Attire 
                        </div>
                    </div>
                    
                    <div class="event">
                        <div class="event-title">🥐 FAREWELL BRUNCH</div>
                        <div class="event-details">
                            <strong>Date:</strong> December 14th, 2025<br>
                            <strong>Time:</strong> 10:00 A.M. - 2:00 P.M.<br>
                            <strong>Location:</strong> Sofitel Legend Santa Clara - Restaurant 1621<br>
                            <strong>Dress Code:</strong> Casual Attire
                        </div>
                    </div>
                </div>
                
                <div class="contact-info">
                    <strong>💡 Important Information</strong><br>
                    If you have any questions or need to make changes to your RSVP, please don\'t hesitate to contact us.<br>
                    We\'re here to help!
                </div>
            </div>
            
            <div class="footer">
                <h3>See you in Cartagena! 🇨🇴</h3>
                <p>With love,</p>
                <p><strong>Asil & Brenda</strong></p>
                <div style="margin-top: 20px; padding-top: 20px; border-top: 1px solid rgba(255,255,255,0.3);">
                    <p style="font-size: 12px;">December 13th, 2025 • Cartagena de Indias, Colombia</p>
                    <p style="font-size: 12px;">This is an automatic confirmation message</p>
                </div>
            </div>
        </div>
    </body>
    </html>';
    
    $headers = [
        'From: rsvp@thekalkavans2025.com',
        'Content-Type: text/html; charset=UTF-8'
    ];
    
    return wp_mail($email, $subject, $message, $headers);
}

/**
 * Función para verificar si todos los invitados declinan todos los eventos
 */
function checkIfAllDecline($guests) {
    $events = ['ceremony', 'reception', 'welcome', 'brunch'];
    
    // Contar total de respuestas decline y total de respuestas posibles
    $total_declines = 0;
    $total_responses = 0;
    
    foreach ($events as $event) {
        if (isset($guests[$event])) {
            foreach ($guests[$event] as $guest_name => $response) {
                $total_responses++;
                if ($response === 'decline') {
                    $total_declines++;
                }
            }
        }
    }
    
    // Si hay respuestas y TODAS son decline, entonces todos declinaron todo
    return $total_responses > 0 && $total_declines === $total_responses;
}

/**
 * Function to send emotional email when all guests decline all events
 */
function sendDeclineEmail($guest_name, $email) {
    $subject = 'RSVP Received – We\'ll Miss You!';
    
    $message = '
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <style>
            body { font-family: "Georgia", serif; line-height: 1.6; color: #333; margin: 0; padding: 0; background: #f5f5f5; }
            .container { max-width: 600px; margin: 0 auto; background: white; }
            .header { background: linear-gradient(135deg, #8B9467, #A5B375); color: white; padding: 40px 30px; text-align: center; }
            .header h1 { margin: 0 0 10px 0; font-size: 28px; font-weight: normal; }
            .header p { margin: 0; font-size: 16px; opacity: 0.9; }
            .content { padding: 40px 30px; }
            .greeting { font-size: 20px; color: #8B9467; margin-bottom: 20px; text-align: center; }
            .message { font-size: 16px; line-height: 1.8; margin-bottom: 30px; text-align: center; }
            .highlight { background: #f9f9f9; padding: 20px; border-left: 4px solid #8B9467; margin: 30px 0; font-style: italic; }
            .footer { background: #8B9467; color: white; padding: 30px; text-align: center; }
            .footer h3 { margin: 0 0 15px 0; font-size: 20px; }
            .footer p { margin: 5px 0; font-size: 14px; opacity: 0.9; }
            .divider { height: 2px; background: linear-gradient(to right, transparent, #8B9467, transparent); margin: 30px 0; }
            .heart { color: #d63384; font-size: 20px; }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>RSVP Received</h1>
                <p>We\'ll Miss You!</p>
            </div>
            
            <div class="content">
                <div class="greeting">
                    Dear ' . $guest_name . ',
                </div>
                
                <div class="message">
                    Thank you for letting us know.<br><br>
                    We\'ll miss you on our special day, but we truly appreciate your kind wishes and thoughts.
                </div>
                
                <div class="divider"></div>
            </div>
            
            <div class="footer">
                <h3>With love,</h3>
                <p><strong>Asil & Brenda</strong></p>
                <div style="margin-top: 20px; padding-top: 20px; border-top: 1px solid rgba(255,255,255,0.3);">
                    <p style="font-size: 12px;">December 13th, 2025 • Cartagena de Indias, Colombia</p>
                </div>
            </div>
        </div>
    </body>
    </html>';
    
    $headers = [
        'From: rsvp@thekalkavans2025.com',
        'Content-Type: text/html; charset=UTF-8'
    ];
    
    return wp_mail($email, $subject, $message, $headers);
}

/**
 * Handle RSVP AJAX requests
 */
function handle_rsvp_ajax() {
    if ($_POST && isset($_POST['action'])) {
        $action = $_POST['action'];
        
        if ($action === 'get_guests') {
            global $rsvp_invitados;
            header('Content-Type: application/json');
            echo json_encode($rsvp_invitados);
            exit;
        }
        
        if ($action === 'submit_rsvp') {
            try {
                // Get data
                $guest_name = $_POST['guest_name'] ?? '';
                $guests_json = $_POST['guests'] ?? '{}';
                $allergies = $_POST['allergies'] ?? '';
                $email = $_POST['email'] ?? '';
                
                // Debug: Log received RAW data
                error_log('RAW DATA: ' . print_r($_POST, true));
                error_log('JSON RAW LENGTH: ' . strlen($guests_json));
                error_log('JSON RAW FIRST 500 CHARS: ' . substr($guests_json, 0, 500));
                
                // Multiple attempts to clean and decode JSON
                $guests = null;
                $attempts = [
                    $guests_json, // Original
                    trim($guests_json), // Trimmed
                    stripslashes($guests_json), // Sin slashes
                    trim(stripslashes($guests_json)), // Ambos
                    html_entity_decode($guests_json), // Decode entities
                    urldecode($guests_json) // URL decode
                ];
                
                foreach ($attempts as $i => $attempt) {
                    error_log("Attempt {$i}: " . substr($attempt, 0, 100));
                    $guests = json_decode($attempt, true);
                    if ($guests !== null && is_array($guests)) {
                        error_log("✅ JSON decoded successfully on attempt {$i}");
                        break;
                    }
                    error_log("❌ Attempt {$i} failed: " . json_last_error_msg());
                }
                
                // Debug: Final result
                error_log('JSON decode result: ' . print_r($guests, true));
                error_log('Final JSON error: ' . json_last_error_msg());
                error_log('Is array check: ' . ($guests ? 'true' : 'false'));
                error_log('Array check: ' . (is_array($guests) ? 'true' : 'false'));
                
                // Enhanced validations
                if (empty($guest_name)) {
                    throw new Exception('Missing primary guest name');
                }
                
                if (empty($email)) {
                    throw new Exception('Missing email');
                }
                
                if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
                    throw new Exception('Invalid email');
                }
                
                // Final validation
                if ($guests === null || $guests === false || !is_array($guests)) {
                    error_log('❌ ALL JSON ATTEMPTS FAILED');
                    error_log('Complete raw JSON: ' . $guests_json);
                    throw new Exception('Error decoding guest JSON - invalid format');
                }
                
                if (!is_array($guests)) {
                    throw new Exception('Guest data is not a valid array');
                }
                
                if (count($guests) === 0) {
                    throw new Exception('No event data in RSVP');
                }
                
                // Log processed data
                error_log('RSVP processed successfully: ' . print_r([
                    'guest' => $guest_name,
                    'email' => $email,
                    'allergies' => $allergies,
                    'guests_count' => count($guests)
                ], true));
                
                // Verificar si todos declinan todos los eventos
                $all_declined = checkIfAllDecline($guests);
                
                // Send actual emails
                $admin_sent = sendAdminEmail($guest_name, $guests, $allergies, $email);
                
                // Enviar correo apropiado al invitado
                if ($all_declined) {
                    $guest_sent = sendDeclineEmail($guest_name, $email);
                    error_log('📧 Correo de decline enviado a: ' . $guest_name);
                } else {
                    $guest_sent = sendGuestEmail($guest_name, $email);
                    error_log('📧 Correo de confirmación enviado a: ' . $guest_name);
                }
                
                // Response with email status
                header('Content-Type: application/json');
                echo json_encode([
                    'success' => true, 
                    'message' => 'RSVP sent successfully',
                    'debug' => [
                        'guest_name' => $guest_name,
                        'email' => $email,
                        'guests_events' => array_keys($guests),
                        'all_declined' => $all_declined,
                        'email_type' => $all_declined ? 'decline' : 'confirmation',
                        'admin_email_sent' => $admin_sent,
                        'guest_email_sent' => $guest_sent
                    ]
                ]);
                
            } catch (Exception $e) {
                error_log('RSVP ERROR: ' . $e->getMessage());
                header('Content-Type: application/json');
                echo json_encode(['success' => false, 'message' => $e->getMessage()]);
            }
            exit;
        }
    }
} 